[[headers]]
  for = "/.well-known/assetlinks.json"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"

[build]
  functions = "netlify/functions"
  publish = "dist"

[dev]
  port = 9999
  targetPort = 5173
  framework = "vite"  
